---
grails:
    cors:
            enabled: true
            allowedHeaders:
                - Content-Type
            mappings:
                /**:
                    allowedOrigins:
                        - "*"
    profile: rest-api
    codegen:
        defaultPackage: pontorestapi
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---

#hibernate:
#    cache:
#        queries: false
#        use_second_level_cache: false
#        use_query_cache: false
#dataSource:
#    pooled: true
#    jmxExport: true
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''##
#
#environments:
#    development:
#        dataSource:
#            dbCreate: create-drop
 #           url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    #pooled: true
    #jmxExport: true
    #driverClassName: org.h2.Driver
    #username: sa
    #password: ''

  #  pooled: true
   # jmxExport: true
   # driverClassName: com.mysql.jdbc.Driver
   # dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   # username: root
   # password: ''

   # pooled: true
   # jmxExport: true
   # driverClassName: org.postgresql.Driver
   # dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect
   # username: postgres
   # password: ''

   pooled: true
   jmxExport: true
   driverClassName: org.postgresql.Driver
   dialect: org.hibernate.dialect.PostgreSQLDialect
   #dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect
   username: gcnasohtatgsuc
   password: 'b0a769e2dc7b5b840177d84fb47b7a1dddb682b470d0f80a58c4682604ef6a5b'



environments:
    development:
        dataSource:
            dbCreate: update
            #url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            #url: jdbc:postgresql://localhost/ponto
            url: jdbc:postgresql://ec2-23-21-128-35.compute-1.amazonaws.com:5432/d3165etku2loer?sslmode=require
            #url: jdbc:postgresql://gcnasohtatgsuc:b0a769e2dc7b5b840177d84fb47b7a1dddb682b470d0f80a58c4682604ef6a5b@ec2-23-21-128-35.compute-1.amazonaws.com:5432/d3165etku2loer?sslmode=require
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
           # url: jdbc:mysql://localhost:3306/ponto
            url: jdbc:postgresql://ec2-23-21-128-35.compute-1.amazonaws.com:5432/d3165etku2loer?sslmode=require

            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
